[package]
name = "qalb-cyber"
version = "0.1.0"
authors = ["Andrew Potter <hello@drewpotter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
argparse = "0.2.2"
figlet-rs = "0.1.3"